### PR TITLE
Fix deprecations

### PR DESCRIPTION
**Pull request by arandilopez**
Use editor.lineTextForBufferRow(row).length instead
```
TextEditor.lineLengthForBufferRow (/opt/atom/resources/app.asar/src/text-editor.js:2839:7)
prefixOfSelection (/home/arandilopez/.atom/packages/autocomplete-phpunit/lib/util/prefixOfSelection.js:22:14)
Object.requestHandler (/home/arandilopez/.atom/packages/autocomplete-phpunit/lib/PHPUnitAssertionsProvider.js:26:21)
<unknown> (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:56)
Array.forEach (native)
AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:234:17)
```

Use TextEditor::getLastSelection() instead
```
TextEditor.getSelection (/opt/atom/resources/app.asar/src/text-editor.js:2963:9)
Object.requestHandler (/home/arandilopez/.atom/packages/autocomplete-phpunit/lib/PHPUnitAssertionsProvider.js:25:28)
<unknown> (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:56)
Array.forEach (native)
AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:234:17)
getSuggestionsFromProviders (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
```
:hand:

### CODE REVIEW

**Comment by CentaurWarchief** [comment]
Hey @arandilopez, thank you very much. I was without time to give it a shot, they mentioned about deprecations in [https://github.com/atom/atom/issues/6867#issue-78571273](atom/issues/6867).

Cheers! :beers:

**Comment by arandilopez** [comment]
You're welcome @CentaurWarchief... I saw this today :smile: 

Regards! :beer:

**Comment by benogle** [comment]
:heart: :green_heart:

**Comment by CentaurWarchief** [comment]
Hey @benogle, here you go:

screenshot from 2015-05-21 23 58 46

;)

**Comment by arandilopez** [comment]
:+1:

**Pull request merged**
